services:
  api:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
      - ./.docker/go-mod:/gomodcache
      - ./.docker/go-build:/gocache
    environment:
      GOMODCACHE: /gomodcache
      GOCACHE: /gocache
