services:
  db:
    image: postgres:17.1-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: social
      # PORT: ${DB_PORT}
      # DB_URL: ${DB_URL}
      # SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      # MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      # MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d social"]
      interval: 5s
      timeout: 3s
      retries: 10
    env_file:
      - .env
  
  redis:
    image: redis:7.4.1-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    ports:
      - 8081:8081
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
  
  migrate:
    image: migrate/migrate:v4.17.1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./cmd/migrate/migrations:/migrations:ro
    command:
      - "-path=/migrations"
      - "-database=postgres://admin:adminpassword@db:5432/social?sslmode=disable"
      - "up"
    restart: "no"
  
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: postgres://admin:adminpassword@db:5432/social?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

volumes:
  db-data:
  redis-data: